server:
  port: 8080

mq:
  # RocketMQ配置
  # 注意：如果不需要使用RocketMQ，请保持以下配置注释状态
  # rocketmq:
  #   # RocketMQ服务器地址，格式：host:port
  #   name-server-addr: localhost:9876
  #   # 生产者组名
  #   producer-group: test-producer-group
  #   # 消费者组名
  #   consumer-group: test-consumer-group
  #   # 发送消息超时时间（毫秒）
  #   send-msg-timeout: 3000

  # Redis测试配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000

  # EMQX配置
  # 注意：默认禁用EMQX，只在需要时启用
  emqx:
    enabled: false
    # 以下配置仅在 enabled 为 true 时生效
    # server-uri: tcp://localhost:1883
    # username: admin
    # password: public
    # client-id: testClient
    # clean-session: true
    # keep-alive-interval: 60

logging:
  level:
    com.example.mq: debug